/**
 * Generate DraftKings deep links for bets
 * Note: DraftKings doesn't support pre-filled bet slips via deep links,
 * but we can link to the event page where users can manually place bets
 */

export function generateDraftKingsLink(
  sport: string,
  homeTeam: string,
  awayTeam: string,
  commenceTime: string
): string {
  // Clean team names for URL
  const cleanTeam = (team: string) =>
    team
      .replace(/\s+/g, '-')
      .replace(/[^a-zA-Z0-9-]/g, '')
      .toLowerCase();

  const home = cleanTeam(homeTeam);
  const away = cleanTeam(awayTeam);

  // Map sports to DraftKings sport paths
  const sportMap: Record<string, string> = {
    americanfootball_nfl: 'nfl',
    americanfootball_ncaaf: 'college-football',
    basketball_nba: 'nba',
    basketball_ncaab: 'college-basketball',
    icehockey_nhl: 'nhl',
    baseball_mlb: 'mlb',
  };

  const dkSport = sportMap[sport] || 'featured';

  // DraftKings event page format
  // Example: https://sportsbook.draftkings.com/leagues/football/nfl
  return `https://sportsbook.draftkings.com/leagues/${getSportCategory(sport)}/${dkSport}`;
}

function getSportCategory(sport: string): string {
  if (sport.includes('football')) return 'football';
  if (sport.includes('basketball')) return 'basketball';
  if (sport.includes('hockey')) return 'hockey';
  if (sport.includes('baseball')) return 'baseball';
  return 'sports';
}

/**
 * Generate a shareable text message for a bet
 */
export function generateBetShareText(bet: {
  event_name: string;
  pick: string;
  odds: number;
  confidence?: number;
  edge?: number;
}): string {
  const oddsStr = bet.odds > 0 ? `+${bet.odds}` : `${bet.odds}`;
  const confidenceStr = bet.confidence
    ? ` | ${bet.confidence.toFixed(1)}/10 confidence`
    : '';
  const edgeStr = bet.edge ? ` | ${bet.edge.toFixed(1)}% edge` : '';

  return `🎯 ${bet.event_name}\n${bet.pick} (${oddsStr})${confidenceStr}${edgeStr}`;
}

/**
 * Generate a shareable text message for a parlay
 */
export function generateParlayShareText(parlay: {
  legs: Array<{
    event_name: string;
    pick: string;
    odds: number;
  }>;
  parlay_odds: number;
  confidence?: number;
  avg_edge?: number;
}): string {
  const header = `🔥 ${parlay.legs.length}-Leg Parlay (${parlay.parlay_odds > 0 ? '+' : ''}${parlay.parlay_odds})`;
  const stats = parlay.confidence
    ? `\nConfidence: ${parlay.confidence.toFixed(1)}/10${parlay.avg_edge ? ` | Avg Edge: ${parlay.avg_edge.toFixed(1)}%` : ''}`
    : '';

  const legs = parlay.legs
    .map((leg, i) => {
      const oddsStr = leg.odds > 0 ? `+${leg.odds}` : `${leg.odds}`;
      return `\n${i + 1}. ${leg.event_name}\n   ${leg.pick} (${oddsStr})`;
    })
    .join('');

  return `${header}${stats}\n${legs}\n\n🤖 Generated by M.R. B.A.L.L.S.`;
}
